### ISSUE TITLE
Error loading library

### ISSUE THREAD

**Issue by dreikanter** [baygeldin/tantiny#12]
Hello! My attempt to require the gem causes a `LoadError`:

```
$ gem install tantiny

Fetching tantiny-0.3.1.gem
Building native extensions. This could take a while...
Successfully installed tantiny-0.3.1
Parsing documentation for tantiny-0.3.1
Installing ri documentation for tantiny-0.3.1
Done installing documentation for tantiny after 0 seconds
1 gem installed

$ irb

irb(main):001:0> require "tantiny"
/Users/alex/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/tantiny-0.3.1/lib/tantiny.rb:18:in `require_relative': cannot load such file -- /Users/alex/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/tantiny-0.3.1/lib/tantiny.so (LoadError)
	from /Users/alex/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/tantiny-0.3.1/lib/tantiny.rb:18:in `<top (required)>'
	from <internal:/Users/alex/.asdf/installs/ruby/3.1.0/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
	from <internal:/Users/alex/.asdf/installs/ruby/3.1.0/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
	from <internal:/Users/alex/.asdf/installs/ruby/3.1.0/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
	from (irb):1:in `<main>'
	from /Users/alex/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/irb-1.4.1/exe/irb:11:in `<top (required)>'
	from /Users/alex/.asdf/installs/ruby/3.1.0/bin/irb:25:in `load'
	from /Users/alex/.asdf/installs/ruby/3.1.0/bin/irb:25:in `<main>'
<internal:/Users/alex/.asdf/installs/ruby/3.1.0/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- tantiny (LoadError)
	from <internal:/Users/alex/.asdf/installs/ruby/3.1.0/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from (irb):1:in `<main>'
	from /Users/alex/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/irb-1.4.1/exe/irb:11:in `<top (required)>'
	from /Users/alex/.asdf/installs/ruby/3.1.0/bin/irb:25:in `load'
	from /Users/alex/.asdf/installs/ruby/3.1.0/bin/irb:25:in `<main>'
```

`tantiny.so` actually exists:

```
ls -al /Users/alex/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/tantiny-0.3.1/lib/tantiny.so
-rwxr-xr-x  1 alex  staff  3706829 Apr 18 21:46 /Users/alex/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/tantiny-0.3.1/lib/tantiny.so
```

I'm running Ruby on MacBook Pro M1. Rust is installed from Homebrew (`brew install rust`).

**Comment by baygeldin** [comment]
Hi! Maybe there is an issue with the precompiled binary. Could you delete the `tantiny.so` file and build it again by running `rake` in `tantiny-0.3.1/ext` directory?

**Comment by dreikanter** [comment]
I've just tried, but cargo generated `dylib` file instead of `so`. I've copied and rename it, but this didn't help. Same error so far. (Sorry, I have no experience with Rust.)

```
cd ~/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/tantiny-0.3.1
cargo rustc --release --lib -- -C link-args=-L~/.asdf/installs/ruby/3.1.0/lib

ls -al target/release/ | grep tantiny
-rw-r--r--    1 alex  staff      564 Apr 18 21:59 libtantiny.d
-rwxr-xr-x    1 alex  staff  3706829 Apr 19 12:32 libtantiny.dylib

cp target/release/libtantiny.dylib lib/tantiny.so
```

**Comment by baygeldin** [comment]
Hmm, interesting 🤔 I'm on Linux, so I can't test it out myself, but could you change the contents of the `lib/tantiny.rb` file to the following code and see if it works this way?

```ruby
# frozen_string_literal: true

require "ruby-next/language/setup"
RubyNext::Language.setup_gem_load_path

require "rutie"
require "concurrent"
require "fileutils"

require "tantiny/version"
require "tantiny/errors"
require "tantiny/helpers"
require "tantiny/schema"
require "tantiny/tokenizer"
require "tantiny/query"
require "tantiny/index"

require 'rutie'

module Tantiny
  Rutie.new(:tantiny).init 'Init_tantiny', __dir__
end
```

**Comment by dreikanter** [comment]
I've just checked, and it works now :)

**Comment by baygeldin** [comment]
Thanks @dreikanter! I've pushed a new release (`3.2`) with the fix. Would be great if you could check it too :)

**Comment by dreikanter** [comment]
@baygeldin Hi! Sorry, but I encountered the same issue after upgrading to 0.3.2:

```
$ gem install tantiny

Fetching tantiny-0.3.2.gem
Building native extensions. This could take a while...
Successfully installed tantiny-0.3.2
Parsing documentation for tantiny-0.3.2
Installing ri documentation for tantiny-0.3.2
Done installing documentation for tantiny after 0 seconds
1 gem installed

$ ruby -e "require 'tantiny'"

/Users/alex/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/fiddle.rb:61:in `initialize': dlopen(/Users/alex/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/tantiny-0.3.2/lib/tantiny.dylib, 0x0009): tried: '/Users/alex/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/tantiny-0.3.2/lib/tantiny.dylib' (no such file), '/usr/local/lib/tantiny.dylib' (no such file), '/usr/lib/tantiny.dylib' (no such file) (Fiddle::DLError)
	from /Users/alex/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/fiddle.rb:61:in `new'
	from /Users/alex/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/fiddle.rb:61:in `dlopen'
	from /Users/alex/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/rutie-0.0.4/lib/rutie.rb:21:in `init'
	from /Users/alex/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/tantiny-0.3.2/lib/tantiny.rb:19:in `<module:Tantiny>'
	from /Users/alex/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/tantiny-0.3.2/lib/tantiny.rb:18:in `<top (required)>'
	from <internal:/Users/alex/.asdf/installs/ruby/3.1.0/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
	from <internal:/Users/alex/.asdf/installs/ruby/3.1.0/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
	from <internal:/Users/alex/.asdf/installs/ruby/3.1.0/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
	from -e:1:in `<main>'
<internal:/Users/alex/.asdf/installs/ruby/3.1.0/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- tantiny (LoadError)
	from <internal:/Users/alex/.asdf/installs/ruby/3.1.0/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from -e:1:in `<main>'
ruby -e "require 'tantiny'"
/Users/alex/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/fiddle.rb:61:in `initialize': dlopen(/Users/alex/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/tantiny-0.3.2/lib/tantiny.dylib, 0x0009): tried: '/Users/alex/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/tantiny-0.3.2/lib/tantiny.dylib' (no such file), '/usr/local/lib/tantiny.dylib' (no such file), '/usr/lib/tantiny.dylib' (no such file) (Fiddle::DLError)
	from /Users/alex/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/fiddle.rb:61:in `new'
	from /Users/alex/.asdf/installs/ruby/3.1.0/lib/ruby/3.1.0/fiddle.rb:61:in `dlopen'
	from /Users/alex/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/rutie-0.0.4/lib/rutie.rb:21:in `init'
	from /Users/alex/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/tantiny-0.3.2/lib/tantiny.rb:19:in `<module:Tantiny>'
	from /Users/alex/.asdf/installs/ruby/3.1.0/lib/ruby/gems/3.1.0/gems/tantiny-0.3.2/lib/tantiny.rb:18:in `<top (required)>'
	from <internal:/Users/alex/.asdf/installs/ruby/3.1.0/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
	from <internal:/Users/alex/.asdf/installs/ruby/3.1.0/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
	from <internal:/Users/alex/.asdf/installs/ruby/3.1.0/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
	from -e:1:in `<main>'
<internal:/Users/alex/.asdf/installs/ruby/3.1.0/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- tantiny (LoadError)
	from <internal:/Users/alex/.asdf/installs/ruby/3.1.0/lib/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from -e:1:in `<main>'
```

Replacing `Rutie.new(:tantiny, lib_path: __dir__, lib_prefix: "").init("Init_tantiny", __dir__)` with `Rutie.new(:tantiny).init 'Init_tantiny', __dir__` in the `lib/tantiny.rb` fixes the problem.

**Comment by baygeldin** [comment]
I see, thanks. There seems to be an issue with how Thermite (https://github.com/malept/thermite) precompiles binaries for macOS. I think I'll have to disable this feature for Macs for now, at least until I get my hands on one and get a chance to come up with a workaround.
